version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/melmacia-system-dashboard:cached
      - ./.ssh:/home/vscode/.ssh:ro
    command: sleep infinity
    # Ejecuta el comando post-creación
    entrypoint: >
      /bin/sh -c "
        sudo chown -R vscode:vscode /workspaces/melmacia-system-dashboard &&
        sudo chmod 700 /home/vscode/.ssh &&
        sudo chmod 600 /home/vscode/.ssh/* &&
        pip3 install -r requirements.txt &&
        python dashboard.py & python background_service.py & wait
      "
    working_dir: /workspaces/melmacia-system-dashboard
    ports:
      - "9000:9000"
    user: vscode