version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12
    volumes:
      - .:/workspaces/melmacia-system-dashboard:cached
      - ./.ssh:/tmp/.ssh:ro
    command: sleep infinity
    # Ejecuta el comando post-creación
    entrypoint: >
      /bin/sh -c "
        sudo mkdir -p /home/vscode/.ssh &&
        sudo cp -r /tmp/.ssh/* /home/vscode/.ssh/ &&
        sudo chown -R vscode:vscode /home/vscode/.ssh &&
        sudo chmod 700 /home/vscode/.ssh &&
        sudo chmod 600 /home/vscode/.ssh/* &&
        sudo -u vscode pip3 install -r requirements.txt &&
        sudo -u vscode python dashboard.py & sudo -u vscode python background_service.py & wait
      "
    working_dir: /workspaces/melmacia-system-dashboard
    ports:
      - "9000:9000"
    user: root