version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # Ejecuta el comando post-creación
    entrypoint: /bin/sh -c "pip3 install -r requirements.txt && exec sleep infinity"