version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    volumes:
      - .:/workspaces/melmacia-system-dashboard
      - ./.ssh:/home/vscode/.ssh:ro
    command: sleep infinity
    working_dir: /workspaces/melmacia-system-dashboard
    ports:
      - "9000:9000"
    user: ${HOST_UID}:${HOST_GID}